----------ROLES------------------
CREATE ROLE EMPLEADO
  IDENTIFIED BY EMPLOYEE;
CREATE ROLE ADMINISTRADOR
  IDENTIFIED BY ADMI;
CREATE ROLE PROPIETARIO
  IDENTIFIED BY OWNERR;

-----------USERS------------
CREATE USER Miguel
  IDENTIFIED BY macs;
CREATE USER Andres
  IDENTIFIED BY alrc;
CREATE USER Carlos
  IDENTIFIED BY cabb;

-------GRANT-----------
GRANT SELECT TO EMPLEADO;
GRANT SELECT TO PROPIETARIO;
GRANT ALL TO ADMINISTRADOR;

--------------GRANT USER--------

GRANT ADMINISTRADOR TO Miguel;
GRANT EMPLEADO TO Andres;
GRANT PROPIETARIO TO Carlos;
